<?php

namespace App\Enums;

enum ServiceLevelEnum: string
{
    case CARGO_CONSOLIDATION = 'CC';
    case DIRECT_EXPORT = 'DE';
    case INTERNATIONAL_FREIGHT_FORWARDING = 'IFF';
    case CARGO_CONSOLIDATION_DIRECT_EXPORT = 'CC, DE';
    case INTERNATIONAL_FREIGHT_FORWARDING_CARGO_CONSOLIDATION = 'IFF, CC';
    case INTERNATIONAL_FREIGHT_FORWARDING_CARGO_CONSOLIDATION_DIRECT_EXPORT = 'IFF, CC, DE';
}
